### ISSUE TITLE
Help-System

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#149]
Build a help-system into fava, which can be accessed via the sidebar menu. Should contain pages and links with basic info and screenshots how fava works. Important content parts:

- [X] How the `fava`-command works
- [x] Beancount Syntax Primer and links to the beancount-documentation (iframes? ;-) )
- [x] How filters work
- [ ] Basic description of all the views

**Comment by corani** [comment]
When building the latest update, I get the following during installation:

```
Installed xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg
Processing dependencies for beancount-fava==0.2.3
Searching for beancount-pygments-lexer>=0.1.1
Reading https://pypi.python.org/simple/beancount-pygments-lexer/
Best match: beancount-pygments-lexer 0.1.1
Downloading https://pypi.python.org/packages/source/b/beancount-pygments-lexer/beancount-pygments-lexer-0.1.1.tar.gz#md5=08f8b21d1df9f8a246df92866e6b255e
Processing beancount-pygments-lexer-0.1.1.tar.gz
Writing /tmp/easy_install-aqmo1t2o/beancount-pygments-lexer-0.1.1/setup.cfg
Running beancount-pygments-lexer-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-aqmo1t2o/beancount-pygments-lexer-0.1.1/egg-dist-tmp-jlyltiji
Traceback (most recent call last):
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "xxx/3.5.1/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-aqmo1t2o/beancount-pygments-lexer-0.1.1/setup.py", line 4, in <module>
    version = __import__('fava').__version__
  File "/tmp/easy_install-aqmo1t2o/beancount-pygments-lexer-0.1.1/beancount_pygments_lexer/__init__.py", line 17, in <module>
  File "/tmp/easy_install-aqmo1t2o/beancount-pygments-lexer-0.1.1/beancount_pygments_lexer/lexer.py", line 14, in <module>
ImportError: No module named 'pygments'
```

Any ideas?

**Comment by aumayr** [comment]
I think you need to run `setup.py` again (`python setup.py develop` or `pip install --editable .`), because there are new requirements (`pygments` for example).

**Comment by corani** [comment]
I always run `setup.py install`, is that not enough?

**Comment by corani** [comment]
`pip install` got rid of the `pygments` related error, now when I start I'm greeted with:

```
Traceback (most recent call last):
  File "xxx/3.5.1/bin/beancount-web", line 9, in <module>
    load_entry_point('beancount-fava==0.2.3', 'console_scripts', 'beancount-web')()
  File "xxx/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "xxx/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "xxx/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "xxx/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/cli.py", line 8, in <module>
    from fava.application import app, load_user_settings
  File "xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/application.py", line 55, in <module>
    app.help_pages = list_help_pages()
  File "xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/application.py", line 46, in list_help_pages
    for page in os.listdir(app.docs_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/../docs'
```

**Comment by aumayr** [comment]
Ahh, I see the error - will fix it. Hold tight.

**Comment by aumayr** [comment]
Fixed in 760ae46357174b940dffd474b4de75a440b9b418 => does it work now for you?

**Comment by corani** [comment]
Yep, thanks!

**Comment by aumayr** [comment]
@corani 👍

**Comment by aumayr** [comment]
https://github.com/aumayr/beancount-sql-queries/issues/7
