### ISSUE TITLE
More graceful error message when port is in use

### ISSUE THREAD

**Issue by corani** [aumayr/fava#172]
Currently, when you start fava while the port is already in use, you get the following exception:

```
Traceback (most recent call last):
  File "/home/daniel/.pyenv/versions/3.5.1/bin/beancount-web", line 9, in <module>
    load_entry_point('beancount-fava==0.2.3', 'console_scripts', 'beancount-web')()
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/cli.py", line 109, in main
    run(sys.argv[1:])
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/beancount_fava-0.2.3-py3.5.egg/fava/cli.py", line 93, in run
    server.serve(port=args.port, host=args.host, debug=args.debug)
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/livereload-2.4.1-py3.5.egg/livereload/server.py", line 283, in serve
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/livereload-2.4.1-py3.5.egg/livereload/server.py", line 241, in application
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tornado/web.py", line 1825, in listen
    server.listen(port, address)
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/daniel/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

This should be replaced with a more graceful error message.

**Comment by aumayr** [comment]
Now looks like this:

```
$ fava example.ledger
[I 160227 17:36:32 server:281] Serving on http://localhost:5000
Error: Can not start webserver because the port/address is already in use.
Please choose another port with the '-p' option. ([Errno 48] Address already in use)
```
