### ISSUE TITLE
Unable to view journal since upgrading

### ISSUE THREAD

**Issue by adamgibbins** [aumayr/fava#225]
I cannot recall the version I was on previously, I think 0.2.3 - however I just upgraded and can now no longer hit /journal, I get the following in debug mode:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/fava/application.py", line 212, in journal
    return render_template('journal.html')
  File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/fava/templates/journal.html", line 2, in top-level template code
    {% set active_page = 'journal' %}
  File "/usr/local/lib/python3.5/site-packages/fava/templates/_layout.html", line 86, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.5/site-packages/fava/templates/journal.html", line 6, in block "content"
    {% with journal = api.journal(), show_tablefilter=True, show_change_and_balance=config['journal-general-show-balances']  %}
  File "/usr/local/lib/python3.5/site-packages/fava/api/__init__.py", line 322, in journal
    self.entries, with_change_and_balance=with_change_and_balance)
  File "/usr/local/lib/python3.5/site-packages/fava/api/__init__.py", line 198, in _journal
    return [serialize_entry(entry) for entry in entries]
  File "/usr/local/lib/python3.5/site-packages/fava/api/__init__.py", line 198, in <listcomp>
    return [serialize_entry(entry) for entry in entries]
  File "/usr/local/lib/python3.5/site-packages/fava/api/serialization.py", line 49, in serialize_entry
    new_entry['postings'] = [serialize_posting(p) for p in entry.postings]
  File "/usr/local/lib/python3.5/site-packages/fava/api/serialization.py", line 49, in <listcomp>
    new_entry['postings'] = [serialize_posting(p) for p in entry.postings]
  File "/usr/local/lib/python3.5/site-packages/fava/api/serialization.py", line 88, in serialize_posting
    _add_metadata(new_posting, posting)
  File "/usr/local/lib/python3.5/site-packages/fava/api/serialization.py", line 115, in _add_metadata
    new_entry['meta']['filename'] = entry.meta['filename']
KeyError: 'filename'
```

Is there any further info I can give to help debug?

Thanks

**Comment by yagebu** [comment]
I can't reproduce this. What version of beancount are you running?

**Comment by adamgibbins** [comment]
Beancount version is 2.0b7. `bean-check` passes fine.

**Comment by yagebu** [comment]
Do you also get this with a minimal beancount file? Do you use any beancount plugins, or do you have any options set that might be relevant to the journal?

**Comment by adamgibbins** [comment]
I just tested, works in 0.2.5, does not work in 0.2.6. I do have plugins but disabling them doesn't resolve.

By process of elimination I've managed to identify 3 transactions similar to this appear to be causing the issue:
```
2015-11-09 * "Example"
  Assets:Broker:Foobar:ISA                                                                   367 ABC @ 6.86376021798365 GBP
  Expenses:Trading:Commission                                                                 12.5 GBP
  Assets:Broker:Foobar:ISA                                                               -2531.5 GBP
```

**Comment by adamgibbins** [comment]
Further digging suggests `option "account_rounding" "RoundingError"` is the cause.

**Comment by yagebu** [comment]
Thank you for the detailed report and the digging! I think I know the cause of this now. Will provide a fix later.

Since 0.2.6 fava will also display posting metadata. For this we have to remove some attributes that we don't want to show (filename and lineno). But for autogenerated postings like the ones that the `account_rounding` option adds, these don't exist of course, so the code fails.

**Comment by yagebu** [comment]
Can you try and see if my fix works for you?

I've attached a source distribution, if you don't want to setup a dev environment. (`pip3 install 0.2.7.dev0.zip` should work)
[0.2.7.dev0.zip](https://github.com/aumayr/fava/files/181429/beancount-fava-0.2.7.dev0.zip)

**Comment by adamgibbins** [comment]
That fixes, thanks for the speedy resolution! :+1:
