### ISSUE TITLE
Broken bar and line charts

### ISSUE THREAD

**Issue by adamgibbins** [aumayr/fava#278]
I'm running current master, since commit [48ecfd68b4b081367fcefc303e241225990428b7](https://github.com/aumayr/fava/commit/48ecfd68b4b081367fcefc303e241225990428b7
) when trying to view any bar charts I receive the JS error:
```app.js:27 Uncaught TypeError: Cannot read property 'series' of undefined```

I can observe this on the Income Statement -> Monthly Net Profit/Monthly Income/Monthly Expenses screens.

Additionally the line chart on the Net Worth page throws:
```app.js:26 Chart-Type "balances" unknown.```
since the same commit.

Finally, when I change the interval for one of the above mentioned charts I recieve the following stack:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1660, in preprocess_request
    func(request.endpoint, request.view_args)
  File "/usr/local/lib/python3.5/site-packages/beancount_fava-0.2.7.dev0-py3.5.egg/fava/application.py", line 338, in pull_beancount_file
    g.beancount_file_slug = values.pop('bfile', None)
AttributeError: 'NoneType' object has no attribute 'pop'
```

Apologies if this is all known and mid-rewrite, feel free to close if thats the case.

**Comment by aumayr** [comment]
For the Javascript-Errors: Did you rebuild the Javascript and CSS assets?

If no: run `make build-js` in the project root to rebuild it.

**Comment by adamgibbins** [comment]
Damn, no, I had not apologies - don't recall ever having run that before and totally missed the instruction, I'd just been using with `python3 setup.py install`. So running `make build-js` now I get:
```
ERROR in ./sass/theme_default.scss
Module build failed: ModuleBuildError: Module build failed: 
  @function compact($vars...) {
 ^
      Functions may not be defined within control directives or other mixins.
      in /Users/aeg/src/fava/fava/static/node_modules/compass-mixins/lib/compass/functions/_lists.scss (line 81, column 3)
    at DependenciesBlock.onModuleBuildFailed (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/aeg/src/fava/fava/static/node_modules/sass-loader/index.js:272:13)
    at /Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:906:35
    at _arrayEach (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:85:13)
    at Object.<anonymous> (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:898:17)
    at Object.callback (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:44:16)
    at options.error (/Users/aeg/src/fava/fava/static/node_modules/node-sass/lib/index.js:274:32)

ERROR in ./sass/theme_alternative.scss
Module build failed: ModuleBuildError: Module build failed: 
  @function compact($vars...) {
 ^
      Functions may not be defined within control directives or other mixins.
      in /Users/aeg/src/fava/fava/static/node_modules/compass-mixins/lib/compass/functions/_lists.scss (line 81, column 3)
    at DependenciesBlock.onModuleBuildFailed (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/aeg/src/fava/fava/static/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/aeg/src/fava/fava/static/node_modules/sass-loader/index.js:272:13)
    at /Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:906:35
    at _arrayEach (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:85:13)
    at Object.<anonymous> (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:898:17)
    at Object.callback (/Users/aeg/src/fava/fava/static/node_modules/async/lib/async.js:44:16)
    at options.error (/Users/aeg/src/fava/fava/static/node_modules/node-sass/lib/index.js:274:32)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader!./~/sass-loader!./sass/theme_default.scss
    Module build failed: 
      @function compact($vars...) {
     ^
          Functions may not be defined within control directives or other mixins.
          in /Users/aeg/src/fava/fava/static/node_modules/compass-mixins/lib/compass/functions/_lists.scss (line 81, column 3)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader!./~/sass-loader!./sass/theme_alternative.scss
    Module build failed: 
      @function compact($vars...) {
     ^
          Functions may not be defined within control directives or other mixins.
          in /Users/aeg/src/fava/fava/static/node_modules/compass-mixins/lib/compass/functions/_lists.scss (line 81, column 3)
```

**Comment by cgrinds** [comment]
Same stacktrace for me. Also tried with a clean workspace.
OSX
```
node --version 
v5.11.0
npm --version
3.8.6
```

**Comment by adamgibbins** [comment]
I've node v6.0.0 and npm 3.8.6, which are the latest available in homebrew.

**Comment by cgrinds** [comment]
I tried node v6, but ran into a hemorrhage of exceptions related to recompiling sass. 
I reverted to 5.11, deleted node_modules, and have the current issue.
@adamgibbins are you sure that you aren't getting lots of exceptions above the one you pasted?

My little bit of googling last night turned up https://github.com/jtangelder/sass-loader/issues/162 and suggested removing node_modules.

**Comment by adamgibbins** [comment]
@cgrinds Nope, all that I have above is what appear to be a bunch of non-fatal warnings:
```
WARNING in app.js from UglifyJs
Condition always true [./~/jquery/dist/jquery.js:9806,0]
Dropping unused variable div [./javascript/charts.js:84,0]
Dropping unused variable labels [./javascript/charts.js:197,0]
Dropping unused variable height [./javascript/charts.js:335,0]
Condition always true [./~/d3/d3.js:9553,0]
Dropping unreachable code [./~/d3/d3.js:9553,75]
Condition always true [./~/urijs/src/URI.js:16,0]
Dropping unreachable code [./~/urijs/src/URI.js:19,3]
Condition always true [./~/urijs/src/punycode.js:511,0]
Dropping unreachable code [./~/urijs/src/punycode.js:518,2]
Side effects in initialization of unused variable freeExports [./~/urijs/src/punycode.js:5,0]
Side effects in initialization of unused variable freeModule [./~/urijs/src/punycode.js:7,0]
Dropping unused variable key [./~/urijs/src/punycode.js:56,0]
Condition always true [./~/urijs/src/IPv6.js:18,0]
Dropping unreachable code [./~/urijs/src/IPv6.js:21,3]
Condition always true [./~/urijs/src/SecondLevelDomains.js:18,0]
Dropping unreachable code [./~/urijs/src/SecondLevelDomains.js:21,3]
Condition always true [./~/clipboard/lib/clipboard.js:2,0]
Dropping unreachable code [./~/clipboard/lib/clipboard.js:4,5]
Declarations in unreachable code! [./~/clipboard/lib/clipboard.js:7,0]
Dropping unused variable mod [./~/clipboard/lib/clipboard.js:7,0]
Condition always true [./~/clipboard/lib/clipboard-action.js:2,0]
Dropping unreachable code [./~/clipboard/lib/clipboard-action.js:4,5]
Declarations in unreachable code! [./~/clipboard/lib/clipboard-action.js:7,0]
Dropping unused variable mod [./~/clipboard/lib/clipboard-action.js:7,0]
Condition always true [./~/mousetrap/mousetrap.js:1016,0]

WARNING in editor.js from UglifyJs
Condition always true [./~/jquery/dist/jquery.js:9806,0]
Condition always true [./~/urijs/src/URI.js:16,0]
Dropping unreachable code [./~/urijs/src/URI.js:19,3]
Condition always true [./~/urijs/src/punycode.js:511,0]
Dropping unreachable code [./~/urijs/src/punycode.js:518,2]
Side effects in initialization of unused variable freeExports [./~/urijs/src/punycode.js:5,0]
Side effects in initialization of unused variable freeModule [./~/urijs/src/punycode.js:7,0]
Dropping unused variable key [./~/urijs/src/punycode.js:56,0]
Condition always true [./~/urijs/src/IPv6.js:18,0]
Dropping unreachable code [./~/urijs/src/IPv6.js:21,3]
Condition always true [./~/urijs/src/SecondLevelDomains.js:18,0]
Dropping unreachable code [./~/urijs/src/SecondLevelDomains.js:21,3]

ERROR in ./sass/theme_alternative.scss
Module build failed: ModuleBuildError: Module build failed: 
  @function compact($vars...) {
```

**Comment by adamgibbins** [comment]
Tried node v5.11, get the same issue (after running make clean).

**Comment by cgrinds** [comment]
Same error on Ubuntu 14.04.1 using node `4.4.3`

**Comment by corani** [comment]
No issues on Ubuntu with node 5.11/npm 3.8.6 (Ubuntu 14.04.4 LTS 64-bit)

On Tue, May 3, 2016 at 9:11 PM, Chris Grindstaff <notifications@github.com>
wrote:

> Same error on Ubuntu 14.04.1 using node 4.4.3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aumayr/fava/issues/278#issuecomment-216522464>
>



-- 
Best regards,
Daniël Bos


Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91

**Comment by cgrinds** [comment]
Hm. Ubuntu (Mint really, 14.04.1 64 bit) with node 5.11.0 and npm 3.8.6 fails with the same error above.
@corani did you do a `make clean` first?

Are we using the same versions? I see
```
> node-sass@3.7.0 install /tmp/fava/fava/static/node_modules/node-sass
Binary downloaded and installed at /tmp/fava/fava/static/node_modules/node-sass/vendor/linux-x64-47/binding.node
> node-sass@3.7.0 postinstall /tmp/fava/fava/static/node_modules/node-sass
"/tmp/fava/fava/static/node_modules/node-sass/vendor/linux-x64-47/binding.node" exists.
├─┬ node-sass@3.7.0
│ └─┬ sass-graph@2.1.1
├── sass-loader@3.2.0
```

**Comment by cgrinds** [comment]
Workaround:
Edit `fava/static/package.json` change `"node-sass": "^3.4.2"` to `"node-sass": "3.4.2"`
this is needed because if you do a fresh install, node will pickup version 3.7.0 instead of 3.4.2.

3.7.0 doesn't work - pretty sure it's caused by [this](https://github.com/sass/node-sass/issues/1474), which points to [this](https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.2v9kdu5a6).

**Comment by adamgibbins** [comment]
@cgrinds Nice find, thank you. Can confirm that fixes all of my issues, including the python `AttributeError: 'NoneType' object has no attribute 'pop'` 👍

**Comment by aumayr** [comment]
Thanks @adamgibbins for reporting and @cgrinds for the fix/workaround!
